install husky, lint-stage, prettier

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,3 +1,8 @@
 #!/usr/bin/env sh
+set -e  # <-- stop the hook if any command fails
+
+echo "🧪 Running tests..."
 npm test
+
+echo "🧹 Running lint-staged..."
 npx lint-staged
